name: CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-test-ship:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.3'

    - name: Set up Docker
      uses: docker/setup-docker-action@v4

    - name: Install Dependencies
      run: |
        python3 -m venv testVenv
        source testVenv/bin/activate
        pip install -r requirements.txt
        pip install flask gunicorn

    - name: Run smoke test
      run: |
        source testVenv/bin/activate
        python3 -m unittest tests/smoke_test.py

    - name: Run unit tests
      run: |
        source testVenv/bin/activate
        python3 -m unittest tests/unit_test.py

    - name: Run integration test
      run: |
        source testVenv/bin/activate
        python3 -m unittest tests/unit_test.py

    - uses: docker/build-push-action@v2
      with:
        tags: test
        load: true
                
    - name: test
      run: | 
        docker container run --rm --detach test echno "hello"
        
      
          
