name: CI Pipeline
on:
  push:
    branches: [ main ]

jobs:
  build-test-ship:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.3'

    - name: Install dependencies
      run: |
        python3 -m venv flaskappenv  
        source flaskappenv/bin/activate
        pip install -r requirements.txt

    - name: Run smoke test
      run: |
        source flaskappenv/bin/activate
        python3 -W ignore -m unittest tests/smoke_test.py

    - name: Run unit test
      run: |
        source flaskappenv/bin/activate
        python3 -W ignore -m unittest tests/unit_test.py
    
    - name: Run integration test
      run: |
        source flaskappenv/bin/activate
        python3 -W ignore -m unittest tests/unit_test.py

    - name: Docker Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build image
      uses: docker/build-push-action@v6
      with:
        context: .
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/test:1.0.1, ${{ secrets.DOCKERHUB_USERNAME }}/test:latest
        push: false

    - name: Test container
      uses: addnab/docker-run-action@v3
      with:
        image: ${{ secrets.DOCKERHUB_USERNAME }}/test:latest
        run: |
          echo "Hello from inside the container. Here is the list output from the root directory..."
          ls /

    - name: Test container comparison
      run: |
        echo "Hello from the GitHub Actions environment. Here is the list output from the root directory for comparison..."
        ls /
    
    - name: Push image
      uses: docker/build-push-action@v6
      with:
        context: .
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/test:1.0, ${{ secrets.DOCKERHUB_USERNAME }}/test:latest
        push: true
